// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaahtzijjyphzkcbghlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthYWh0emlqanlwaHprY2JnaGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjgyODEsImV4cCI6MjA2ODU0NDI4MX0.2jkoJN-ZfWSGoome0tlMD1iZIkEHh3CX69YX-wj64aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});